# Generated by Django 5.1.2 on 2024-11-13 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'متن نظر باید حداقل 2 کاراکتر باشد')]),
        ),
    ]
