# Generated by Django 5.1.2 on 2024-11-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنتها'},
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
