# Generated by Django 5.1.2 on 2024-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='اسلاگ'),
        ),
    ]
