# Generated by Django 5.1.2 on 2024-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_joinus'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='join_us/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
