# Generated by Django 5.1.2 on 2024-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_joinus_background_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/banners/'),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='media/join_us/'),
        ),
    ]
