"""
Django settings for Assemble project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w!y_ye8&vcaz%5^vd1ujq$__dqpbb6(jmd(m)&p6cmla77!69t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'hamednice.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'mptt',
    "azbankgateways",
    'widget_tweaks',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'django.contrib.postgres',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'category',
    'products',
    "carts",
    'orders',
    'comments',
    'rating',
    'blogs',
    'main',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'blogs.middleware.SimpleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
ROOT_URLCONF = 'Assemble.urls'
AUTH_USER_MODEL = 'accounts.Account'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Assemble.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'assemble',
        'USER': os.environ.get('db_user'),
        'PASSWORD': os.environ.get('db_password'),
        'HOST': os.environ.get('db_host'),
        'PORT': os.environ.get('db_port'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = 'media/'
MEDIA_root = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_URL = 'http://127.0.0.1:8000'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "hameddjf106@gmail.com"
CONTACT_EMAIL = "hameddjf106@gmail.com"
EMAIL_HOST_PASSWORD = "aaas ypux cauw lbho"
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

AZ_IRANIAN_BANK_GATEWAYS = {
    'GATEWAYS': {
        'ZARINPAL': {
            # 'MERCHANT_CODE': 'c9f5d404-1e0f-42d4-9a0d-b17e2e3700c3',
            # 'MERCHANT_CODE': '92d1635b-4155-4d64-8bdc-87e89755ea6b',
            'MERCHANT_CODE': '9a668b46-5577-4561-93a8-b24ac3a9d24d',
            'METHOD': 'GET',  # GET or POST
            'SANDBOX': 1,  # 0 disable, 1 active
        },
        'IDPAY': {
            'MERCHANT_CODE': 'ced73ac8-9ec9-40e6-aa47-08757df1be16',
            'METHOD': 'GET',  # GET or POST
            'X_SANDBOX': 1,  # 0 disable, 1 active
        },
    },
    'IS_SAMPLE_FORM_ENABLE': False,  # disable sample form
    'DEFAULT': 'IDPAY',  # set IDPay as the default gateway
    'CURRENCY': 'IRR',  # set the currency
    'TRACKING_CODE_QUERY_PARAM': 'tc',  # tracking code query parameter
    'TRACKING_CODE_LENGTH': 16,  # tracking code length
    'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader',
    'BANK_PRIORITIES': [
        'IDPAY',
    ],  # IDPay priority
    'IS_SAFE_GET_GATEWAY_PAYMENT': True,  # enable secure payment
    'CUSTOM_APP': None,  # optional
}
IS_SAFE_GET_GATEWAY_PAYMENT = True


JAZZMIN_SETTINGS = {
    "site_title": "داشبورد",
    "site_header": "Assemble",
    "site_brand": "Assemble",
    "welcome_sign": "خوش امدین به پنل ادمین Assemble",
    "copyright": "Assemble",
    "order_sidebar_by": "Assemble",
    "show_sidebar": True,
    "show_header": True,
    "navigation_expanded": False,
    "custom_css": "css/custom.css",
}
# آدرس JS سفارشی اگر نیاز دارید
# JAZZMIN_SETTINGS["custom_js"] = ("your_custom_js.js",)


# Google OAuth2 settings

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'accounts.views.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '289449627532-v8jea14c5oirdhslfacma9ki13tv38g8.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:address_list'
LOGOUT_REDIRECT_URL = 'accounts:login'
# allauth
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_AUTO_SIGNUP = True

ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_SIGNUP_FORM = {'signup': 'accounts.forms.SignUpForm'}
ACCOUNT_LOGIN_FORM = {'login': 'accounts.forms.LoginForm'}
