# Generated by Django 4.2.7 on 2024-12-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='قیمت کل'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='کد پیگیری')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('successful', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_record', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='azbankgateways.bank', verbose_name='رکورد بانکی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
