# Generated by Django 5.1.2 on 2024-11-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_tag_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RAM', 'رم'), ('MOTHERBOARD', 'مادربرد'), ('GRAFIC', 'گرافیک')], max_length=16)),
                ('value', models.CharField(max_length=16)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='category.brand')),
            ],
            options={
                'verbose_name': 'قطعه کیس',
                'verbose_name_plural': 'قطعات کیس',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=248)),
                ('price', models.IntegerField(default=0)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('poster', models.ImageField(blank=True, default=None, null=True, upload_to='media/products/poster/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='category.brand')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('parts', models.ManyToManyField(blank=True, related_name='parts_product', to='products.parts')),
                ('tags', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.tag')),
            ],
            options={
                'verbose_name': 'کیس',
                'verbose_name_plural': 'کیسها',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/products/images/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='products.products')),
            ],
            options={
                'verbose_name': 'تصاویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ('product__name',),
            },
        ),
        migrations.CreateModel(
            name='SpacialsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='spacial_products', to='products.products')),
            ],
            options={
                'verbose_name': 'کیس ویژه',
                'verbose_name_plural': 'کیسهای ویژه',
                'ordering': ('product__name',),
            },
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name'], name='products_pr_name_cec4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['create_at'], name='products_pr_create__59d077_idx'),
        ),
    ]
