# Generated by Django 5.1.2 on 2024-11-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_tag_alter_brand_logo_alter_category_image_and_more'),
        ('products', '0002_alter_products_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='product_parts', to='products.parts'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='product_tags', to='category.tag'),
        ),
    ]
