# Generated by Django 4.2.7 on 2024-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_tag_alter_brand_logo_alter_category_image_and_more'),
        ('products', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_tags', to='category.tag'),
        ),
    ]
